_format_version: "2.1"
_transform: true

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-open
        paths:
          - /auth/v1/verify
        methods:
          - GET
          - POST
        strip_path: true
  - name: auth-v1-open-callback
    url: http://auth:9999/callback
    routes:
      - name: auth-v1-open-callback
        paths:
          - /auth/v1/callback
        methods:
          - GET
          - POST
        strip_path: true
  - name: auth-v1-open-authorize
    url: http://auth:9999/authorize
    routes:
      - name: auth-v1-open-authorize
        paths:
          - /auth/v1/authorize
        methods:
          - GET
          - POST
        strip_path: true
  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1
        paths:
          - /rest/v1/
        strip_path: true
  - name: realtime-v1
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1
        paths:
          - /realtime/v1/
        strip_path: true
  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1
        paths:
          - /storage/v1/
        strip_path: true
  - name: meta
    url: http://meta:8080/
    routes:
      - name: meta
        paths:
          - /meta/
        strip_path: true
